[2025-05-02T04:18:36.897+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T04:18:36.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_gcs.upload_to_gcs manual__2025-05-02T04:18:25.733944+00:00 [queued]>
[2025-05-02T04:18:36.943+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_gcs.upload_to_gcs manual__2025-05-02T04:18:25.733944+00:00 [queued]>
[2025-05-02T04:18:36.975+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-02T04:18:37.133+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2025-05-02 04:18:25.733944+00:00
[2025-05-02T04:18:37.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1505) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T04:18:37.146+0000] {standard_task_runner.py:63} INFO - Started process 1507 to run task
[2025-05-02T04:18:37.146+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_gcs', 'upload_to_gcs', 'manual__2025-05-02T04:18:25.733944+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_gcs_dag.py', '--cfg-path', '/tmp/tmpuldhi49t']
[2025-05-02T04:18:37.148+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask upload_to_gcs
[2025-05-02T04:18:37.429+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_gcs.upload_to_gcs manual__2025-05-02T04:18:25.733944+00:00 [running]> on host 34c72fae0f8a
[2025-05-02T04:18:37.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_gcs' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T04:18:25.733944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T04:18:25.733944+00:00'
[2025-05-02T04:18:37.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T04:18:37.827+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-05-02T04:18:37.836+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-05-02T04:18:37.873+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T04:18:37.876+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mysql_to_gcs_dag.py", line 23, in upload_to_gcs
    gcs_hook.upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 528, in upload
    client = self.get_conn()
             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 173, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 332, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 308, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 371, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 245, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 295, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/gcs-key.json'
[2025-05-02T04:18:37.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=mysql_to_gcs, task_id=upload_to_gcs, run_id=manual__2025-05-02T04:18:25.733944+00:00, execution_date=20250502T041825, start_date=20250502T041836, end_date=20250502T041837
[2025-05-02T04:18:38.078+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task upload_to_gcs ([Errno 2] No such file or directory: '/opt/airflow/gcs-key.json'; 1507)
[2025-05-02T04:18:38.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-02T04:18:38.196+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T04:18:38.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
