[2025-05-02T06:35:54.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T06:35:54.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-02T06:35:40.647484+00:00 [queued]>
[2025-05-02T06:35:54.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-02T06:35:40.647484+00:00 [queued]>
[2025-05-02T06:35:54.430+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-02T06:35:54.518+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2025-05-02 06:35:40.647484+00:00
[2025-05-02T06:35:54.530+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T06:35:54.535+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2025-05-02T06:35:54.541+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_gcs', 'extract_from_mysql', 'manual__2025-05-02T06:35:40.647484+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_gcs_dag.py', '--cfg-path', '/tmp/tmpnmosmkrk']
[2025-05-02T06:35:54.575+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask extract_from_mysql
[2025-05-02T06:35:54.696+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-02T06:35:40.647484+00:00 [running]> on host c04d18144907
[2025-05-02T06:35:54.976+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_gcs' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T06:35:40.647484+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T06:35:40.647484+00:00'
[2025-05-02T06:35:54.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T06:35:55.008+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2025-05-02T06:35:57.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:263: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-05-02T06:35:57.736+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-02T06:35:57.742+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T06:35:57.769+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_gcs, task_id=extract_from_mysql, run_id=manual__2025-05-02T06:35:40.647484+00:00, execution_date=20250502T063540, start_date=20250502T063554, end_date=20250502T063557
[2025-05-02T06:35:57.940+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-02T06:35:58.063+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T06:35:58.129+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
