[2025-05-01T16:37:22.404+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-01T16:36:44.212190+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
