[2025-05-01T17:28:36.143+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T17:28:36.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-01T17:28:12.986075+00:00 [queued]>
[2025-05-01T17:28:36.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-01T17:28:12.986075+00:00 [queued]>
[2025-05-01T17:28:36.241+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-01T17:28:36.302+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_from_mysql> on 2025-05-01 17:28:12.986075+00:00
[2025-05-01T17:28:36.337+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-01T17:28:36.330+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_to_gcs', 'extract_from_mysql', 'manual__2025-05-01T17:28:12.986075+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/mysql_to_gcs_dag.py', '--cfg-path', '/tmp/tmpmomrya8o']
[2025-05-01T17:28:36.353+0000] {standard_task_runner.py:63} INFO - Started process 1283 to run task
[2025-05-01T17:28:36.357+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_from_mysql
[2025-05-01T17:28:36.669+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_gcs.extract_from_mysql manual__2025-05-01T17:28:12.986075+00:00 [running]> on host 34c72fae0f8a
[2025-05-01T17:28:37.260+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_to_gcs' AIRFLOW_CTX_TASK_ID='extract_from_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T17:28:12.986075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T17:28:12.986075+00:00'
[2025-05-01T17:28:37.292+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T17:28:37.318+0000] {base.py:84} INFO - Using connection ID 'mysql_default' for task execution.
[2025-05-01T17:28:38.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:263: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2025-05-01T17:28:39.318+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-01T17:28:39.328+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T17:28:39.356+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_to_gcs, task_id=extract_from_mysql, run_id=manual__2025-05-01T17:28:12.986075+00:00, execution_date=20250501T172812, start_date=20250501T172836, end_date=20250501T172839
[2025-05-01T17:28:39.507+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-01T17:28:39.656+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-01T17:28:39.724+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
